apiVersion: v1
kind: Namespace
metadata:
  name: netdev


---

apiVersion: v1
kind: Pod
metadata:
  name: react-app
  namespace: netdev
  labels:
    app: react
spec:
  containers:
  - name: react-app
    image: netdevopsaslan/react_app:latest
    #imagePullPolicy: Never

---

apiVersion: v1
kind: Service
metadata:
  name: react-app
  namespace: netdev
  labels:
    app: react
spec:
  ports:
  - port: 4884
    protocol: TCP
  selector:
    app: react

---

apiVersion: v1
kind: Pod
metadata:
  name: java-app
  namespace: netdev
  labels:
    app: java
spec:
  containers:
  - name: java-app
    image: netdevopsaslan/java_app:latest
    # imagePullPolicy: Never

---

apiVersion: v1
kind: Service
metadata:
  name: java-back
  namespace: netdev
  labels:
    app: java
spec:
  ports:
  - port: 8080
    protocol: TCP
  selector:
    app: java

---

apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: netdev
  labels:
    app: nginx
spec:
  containers:
  - name: nginx
    image: netdevopsaslan/nginx:latest

---

apiVersion: v1
kind: Service
metadata:
  name: nginx-front
  namespace: netdev
  labels:
    app: nginx
spec:
  ports:
  - port: 80
    protocol: TCP
  type: LoadBalancer
  selector:
    app: nginx
